# Generated by Django 4.2 on 2023-04-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uthusuario',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='uthusuario',
            name='first_name',
            field=models.CharField(default='default_first_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='uthusuario',
            name='last_name',
            field=models.CharField(default='default_last_name', max_length=30),
        ),
    ]
