# Generated by Django 4.2 on 2023-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
