# Generated by Django 4.2 on 2023-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_perfil_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
