# Generated by Django 4.2 on 2023-04-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_alter_perfil_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
