# Generated by Django 4.2 on 2023-04-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
        ('perfiles', '0005_remove_perfil_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera'),
        ),
    ]
