# Generated by Django 4.2 on 2023-04-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_relaciones_perfil_siguiendo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciones',
            name='usuario_seguido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blanco', to='perfiles.perfil'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='usuario_siguiendo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='perfiles.perfil'),
        ),
    ]
