# Generated by Django 4.2 on 2023-04-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0009_alter_relaciones_usuario_seguido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciones',
            name='usuario_seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanco', to='perfiles.perfil'),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='usuario_siguiendo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='perfiles.perfil'),
        ),
    ]
