# Generated by Django 4.2 on 2023-04-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0010_alter_relaciones_usuario_seguido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='siguiendo',
        ),
    ]
