# Generated by Django 4.2 on 2023-04-06 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0002_grupo_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
    ]
