# Generated by Django 4.2 on 2023-04-06 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0003_grupo_activo_alter_grupo_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, null=True, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
    ]
