# Generated by Django 4.2 on 2023-04-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0007_alter_grupo_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nombre de Grupo'),
        ),
    ]
