# Generated by Django 4.2 on 2023-04-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0009_alter_grupo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(default=None, max_length=100, verbose_name='Nombre de Grupo'),
        ),
    ]
