# Generated by Django 4.2 on 2023-04-07 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grupos', '0010_alter_grupo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, default=None, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
    ]
