# Generated by Django 4.2 on 2023-04-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera',
            old_name='carrera',
            new_name='nombre_carrera',
        ),
    ]
