# Generated by Django 4.2 on 2023-04-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default=None, upload_to='archivos')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
            ],
        ),
    ]
