# Generated by Django 4.2 on 2023-04-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_alter_grupo_usuarios'),
        ('archivos', '0004_alter_archivo_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo'),
        ),
    ]
